name: collect-hourly

on:
  schedule:
    # Every hour at :00
    - cron: "0 * * * *"
  # Let you run it manually any time
  workflow_dispatch: {}

# Prevent overlapping runs from clobbering each other
concurrency:
  group: collect-hourly
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest

    # Needed so the job can push data.json back to the repo
    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # so rebase works properly

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        run: python collector.py

      - name: Commit data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          # Make sure we’re up to date before pushing (avoids non–fast-forward)
          git pull --rebase origin main || true
          git add data.json
          git commit -m "Update data.json [ci skip]" || echo "No changes to commit"
          git push origin HEAD:main
