name: collect-hourly

on:
  schedule:
    - cron: '0,30 * * * *'   # every 30 minutes
  workflow_dispatch:

concurrency:
  group: collect-hourly
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # we need full history for rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -U feedparser requests pyyaml python-dateutil beautifulsoup4 \
                         langdetect deep-translator pytz pandas pydeck

      # --- IMPORTANT: pull/rebase BEFORE we generate files ---
      - name: Pull latest main
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout main
          git pull --rebase --autostash origin main

      - name: Run collector
        env:
          STATUS_FILE: status.json
        run: |
          python collector.py
          echo "Collector finished."

      - name: Commit data.json (and status.json) if changed
        run: |
          set -e
          CHANGED=0
          git add -N data.json status.json 2>/dev/null || true     # stage-as-intent, to let diff notice changes
          if ! git diff --quiet -- data.json status.json; then
            git add data.json status.json 2>/dev/null || true
            git commit -m "Update data.json [skip ci]"
            CHANGED=1
          else
            echo "No changes to commit."
          fi
          if [ "$CHANGED" = "1" ]; then
            git push origin HEAD:main
          fi
