name: collect-halfhourly

on:
  schedule:
    # Every 30 minutes (at :00 and :30)
    - cron: "*/30 * * * *"
  # Manual run option
  workflow_dispatch: {}

# Prevent overlapping runs
concurrency:
  group: collect-halfhourly
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        run: python collector.py

      - name: Commit data.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          git pull --rebase origin main || true
          git add data.json
          git commit -m "Update data.json [ci skip]" || echo "No changes to commit"
          git push origin HEAD:main
